export const PACKAGES = {
  basic: {
    name: 'Basic Stole',
    price: 89,
    available: false,
    features: [
      'Black base with traditional green-yellow-red stripes',
      'Year personalization on both panels',
      'Classic woven kente finish',
      'Two-week delivery window',
    ],
    limitations: {
      colors: 1,
      textOnly: true,
      fonts: ['serif'],
    },
  },
  standard: {
    name: 'Standard Stole',
    price: 120,
    available: true,
    features: [
      'Black base with signature motif placement',
      'Includes graduate name and year embroidery',
      'Choice of accent color striping',
      'Motif selection from curated library',
      'Ten-day delivery window',
    ],
    limitations: {
      colors: 2,
      graphics: true,
      fonts: ['serif', 'sans-serif', 'script'],
    },
  },
  custom: {
    name: 'Customized Woven Stole',
    price: 199,
    available: false,
    features: [
      'Fully personalized color layout (up to four colors)',
      'Custom text on both panels with advanced font styles',
      'Motif and symbol layering for a bespoke look',
      'Hand-finished woven construction',
      'Metallic thread enhancement option',
      'One-week rush delivery available',
    ],
    limitations: {
      colors: 4,
      graphics: true,
      metallic: true,
      fonts: ['serif', 'sans-serif', 'script', 'modern', 'elegant', 'bold', 'cursive', 'decorative'],
    },
  },
};

export const FABRICS = {
  basic: ['Classic Woven Kente'],
  standard: ['Classic Woven Kente', 'Matte Satin'],
  custom: ['Heritage Handwoven Kente', 'Matte Satin', 'Heritage Brocade'],
};

export const SYMBOLS = [
  { name: 'Star', icon: '⭐' },
  { name: 'Heart', icon: '❤️' },
  { name: 'Graduation Cap', icon: '🎓' },
  { name: 'Book', icon: '📚' },
  { name: 'Trophy', icon: '🏆' },
  { name: 'Globe', icon: '🌍' },
  { name: 'Peace Sign', icon: '☮️' },
  { name: 'Infinity', icon: '∞' },
  { name: 'Cross', icon: '✝️' },
  { name: 'Ankh', icon: '☥' },
];

export const ORDER_STATUSES = [
  { value: 'pending', label: 'Pending', color: 'bg-yellow-500' },
  { value: 'confirmed', label: 'Confirmed', color: 'bg-blue-500' },
  { value: 'in_production', label: 'In Production', color: 'bg-purple-500' },
  { value: 'completed', label: 'Completed', color: 'bg-green-500' },
  { value: 'delivered', label: 'Delivered', color: 'bg-gray-500' },
];

export const KENTE_COLORS = [
  { name: 'Gold', hex: '#D4AF37' },
  { name: 'Black', hex: '#000000' },
  { name: 'Red', hex: '#DC2626' },
  { name: 'Green', hex: '#16A34A' },
  { name: 'Blue', hex: '#2563EB' },
  { name: 'White', hex: '#FFFFFF' },
  { name: 'Yellow', hex: '#EAB308' },
  { name: 'Orange', hex: '#EA580C' },
];

export const UNIVERSITY_ACADEMICS = {
  'University of Ghana': {
    colleges: {
      'College of Basic and Applied Sciences': [
        'BSc Actuarial Science',
        'BSc Animal Biology and Conservation Science',
        'BSc Biochemistry, Cell and Molecular Biology',
        'BSc Botany',
        'BSc Plant and Environmental Biology',
        'BSc Chemistry',
        'BSc Computer Science',
        'BSc Earth Science',
        'BSc Geology',
        'BSc Information Technology',
        'BSc Mathematics',
        'BSc Marine and Fisheries Sciences',
        'BSc Nutrition and Food Science',
        'BSc Physics',
        'BSc Statistics',
        'BSc Biomedical Engineering',
        'BSc Computer Engineering',
        'BSc Food Process Engineering',
        'BSc Materials Science and Engineering',
      ],
      'College of Health Sciences': [
        'MBChB Medicine and Surgery',
        'BDS Dental Surgery',
        'BSc Dietetics',
        'BSc Medical Laboratory Science',
        'BSc Occupational Therapy',
        'BSc Physiotherapy',
        'BSc Radiography',
        'BSc Nursing',
      ],
      'College of Humanities': [
        'BA Economics',
        'BA Political Science',
        'BA Sociology',
        'BA Geography and Resource Development',
        'BA History',
        'BA Philosophy and Classics',
        'BA Archaeology and Heritage Studies',
        'BA Psychology',
        'BA Social Work',
        'BA Information Studies',
        'BA English',
        'BA French',
        'BA Linguistics',
        'BA Theatre Arts',
        'LLB Law',
        'BSc Business Administration (Accounting)',
        'BSc Business Administration (Banking and Finance)',
        'BSc Business Administration (Human Resource Management)',
        'BSc Business Administration (Public Administration)',
        'BSc Business Administration (Health Services Management)',
        'BSc Business Administration (Insurance)',
        'BSc Business Administration (Marketing)',
        'BFA Dance',
        'BFA Music',
        'BFA Theatre Arts',
      ],
      'College of Education': [
        'BEd Early Grade Education',
        'BEd Upper Primary Education',
        'BEd Junior High School Education',
        'BEd Mathematics Education',
        'BEd Physics Education',
        'BEd Chemistry Education',
        'BEd Biology Education',
        'BEd English Education',
        'BEd French Education',
        'BEd Spanish Education',
        'BEd Performing Arts Education (Music)',
        'BEd Performing Arts Education (Dance)',
        'BEd Performing Arts Education (Theatre Arts)',
        'BEd Information and Communication Technology Education',
        'BEd Consumer Sciences Education',
      ],
      'School of Graduate Studies': ['Graduate Research Programmes'],
    },
  },
} as const;
